### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by elsbrock** [vega/svelte-vega#968]
Just wanted to try this out in a Svelte 4 project, and immediately stumbled over this problem:

```
Cannot use import statement outside a module

/Users/else/ghq/github.com/elsbrock/svelte-vega-repro/node_modules/vega-embed/build/vega-embed.module.js:1
import { applyPatch } from 'fast-json-patch';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1350:18)
    at Module._compile (node:internal/modules/cjs/loader:1379:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at cjsLoader (node:internal/modules/esm/translators:318:15)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
    at async nodeImport (file:///Users/else/ghq/github.com/elsbrock/svelte-vega-repro/node_modules/vite/dist
```

Repro: https://github.com/elsbrock/svelte-vega-repro (this is a skeleton Svelte 4 project as generated by `npx svelte@4 create-app`.

Not the biggest JS expert; to me it looks like the affected module is already declaring itself as `"type": "module"`.

Thank you for providing this module.

```
  System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 46.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /nix/store/rz5da1id31jgyax1yb6dms0mzpxkywds-nodejs-22.2.0/bin/node
    npm: 10.7.0 - /nix/store/rz5da1id31jgyax1yb6dms0mzpxkywds-nodejs-22.2.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.0
  npmPackages:
    svelte: ^3.54.0 => 3.59.2
```

**Comment by domoritz** [comment]
Hmm, odd. Do you have an idea what could be wrong? Could you compare your setup to https://github.com/vega/svelte-vega/tree/main/packages/svelte-vega-sample?

**Comment by elsbrock** [comment]
I'm sorry, but can I get that to run? Tried the following:

```
❯ yarn install
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "commitizen > cz-conventional-changelog > @commitlint/load > cosmiconfig-typescript-loader@5.0.0" has unmet peer dependency "@types/node@*".
warning " > prettier-plugin-svelte@3.2.3" has unmet peer dependency "svelte@^3.2.0 || ^4.0.0-next.0 || ^5.0.0-next.0".
warning " > svelte-vega@1.2.0" has unmet peer dependency "svelte@^3.54.0 || ^4.0.0".
warning " > svelte-vega@1.2.0" has unmet peer dependency "vega@*".
warning " > svelte-vega@1.2.0" has unmet peer dependency "vega-lite@*".
warning " > svelte-vega@1.2.0" has unmet peer dependency "vega-embed@*".
warning "workspace-aggregator-dca14ed5-6be8-491e-9403-299e625f16c2 > svelte-vega > @sveltejs/kit@2.5.7" has unmet peer dependency "@sveltejs/vite-plugin-svelte@^3.0.0".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
Done in 5.23s.
❯ cd packages/sveltekit-vega-sample
/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample
❯ yarn install
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
warning svelte-check > svelte-preprocess > sorcery > sander > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
warning svelte-check > svelte-preprocess > sorcery > sander > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning svelte-check > svelte-preprocess > sorcery > sander > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > vega-embed@6.26.0" has unmet peer dependency "vega@^5.21.0".
warning " > vega-embed@6.26.0" has unmet peer dependency "vega-lite@*".
warning "vega-embed > vega-themes@2.15.0" has unmet peer dependency "vega@*".
warning "vega-embed > vega-themes@2.15.0" has unmet peer dependency "vega-lite@*".
warning " > @sveltejs/kit@2.7.4" has unmet peer dependency "@sveltejs/vite-plugin-svelte@^3.0.0 || ^4.0.0-next.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 5.65s.
❯ yarn dev
yarn run v1.22.22
$ vite dev
Forced re-optimization of dependencies

  VITE v5.4.10  ready in 956 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Error:   Failed to scan for dependencies from entries:
  /home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/src/routes/+page.svelte

  ✘ [ERROR] Failed to resolve entry for package "svelte-vega". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/esbuild/lib/main.js:1225:21:
      1225 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46637:15)
    at resolvePackageEntry (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46634:3)
    at tryNodeResolve (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46450:16)
    at ResolveIdContext.resolveId (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46200:19)
    at PluginContainer.resolveId (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49015:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49627:22)
    at async file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49798:28
    at async requestCallbacks.on-resolve (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:1225:22)
    at async handleRequest (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:647:11)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49786:13)
    at handlePlugins (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:699:5)
    at /home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildScanner (file:///home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49573:24)

  The plugin "vite:dep-scan" was triggered by this import

    script:/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/src/routes/+page.svelte?id=0:117:7:
      117 │ import 'svelte-vega'
          ╵        ~~~~~~~~~~~~~


    at failureErrorWithLog (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:1472:15)
    at /home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:943:7)
    at /home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:955:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:954:54)
    at handleRequest (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:647:17)
    at handleIncomingPacket (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:672:7)
    at Socket.readFromStdout (/home/else/ghq/github.com/vega/svelte-vega/packages/sveltekit-vega-sample/node_modules/esbuild/lib/main.js:600:7)
```

**Comment by domoritz** [comment]
You don't need to install anything in the same package. Try just `yarn && yarn sample:svelte` from the top-level. Make sure to remove any changes you added.

**Comment by domoritz** [comment]
It looks like an issue with esm. If we switch to esm for Vega embed, things break because some dependencies don't support esm.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/svelte-vega/pull/971

**Comment by elsbrock** [comment]
Thank you! Apologies I didn't get back yet. I'll give it a try.
